language: java
install: true

jdk:
- oraclejdk8

script:
- ./gradlew build --stacktrace

notifications:
  slack:
    rooms:
    - codingnomads:DAXjUWJQ6OaVTvCtUssOHtFy#mexico-2018-travis
    on_success: always
    on_failure: always