spring:
  application:
    name: diveapp
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DB_HOST:localhost}:3306/diveapp?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_DB_USERNAME:test}
    password: ${MYSQL_DB_PASSWORD:test}
server:
  port: 8080